version: 2

models:
  - name: stg_example__source_data
    description: "サンプルソースデータのステージングモデル"
    columns:
      - name: id
        description: "レコードの一意識別子"
        data_tests:
          - unique
          - not_null
