version: 2

models:
  - name: fct_example
    description: "サンプルファクトテーブル：id=1のレコードのみを含む"
    columns:
      - name: id
        description: "レコードの一意識別子（値は常に1）"
        data_tests:
          - unique
          - not_null
          - accepted_values:
              arguments:
                values: [1]
  - name: dim_prefectures
    description: "都道府県ディメンションテーブル"
    columns:
      - name: prefecture_code
        description: "都道府県コード（JIS X0401準拠）"
        data_tests:
          - unique
          - not_null
      - name: prefecture_name
        description: "都道府県名"
        data_tests:
          - not_null
