version: 2

models:
  - name: fct_example
    description: "サンプル事実テーブル：id=1のレコードのみを含む"
    columns:
      - name: id
        description: "レコードの一意識別子（値は常に1）"
        data_tests:
          - unique
          - not_null
          - accepted_values:
              arguments:
                values: [1]
